In [1]:
import json
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
from results import Results

In [4]:
targetSizeWidth = 112
targetSizeHeight = 112
targetSize = (targetSizeWidth, targetSizeHeight)
batchSize = 32
directory_filename='./ModeloPablo20'
testDirectory='/data'

In [5]:
def load(filename: str):
    """Loads a trained CNN model and the corresponding preprocessing information.

    Args:
        filename: Relative path to the file without the extension.

    """
    # Load Keras model
    model = tf.keras.models.load_model(filename + '.h5')

    # Load base model information
    with open(filename + '.json') as f:
        model_name = json.load(f)
    return model

cnn=load(directory_filename)

In [8]:
def predict(model,test_dir,dataset_name:str, save: bool = True):
    """Evaluates a new set of images using the trained CNN.

    Args:
        test_dir: Relative path to the validation directory (e.g., 'dataset/test').
        dataset_name: Dataset descriptive name.
        save: Save results to an Excel file.

    """
    # Configure loading and pre-processing functions
    print('Reading test data...')
    test_datagen = ImageDataGenerator(rescale=1./255)

    test_generator = test_datagen.flow_from_directory(
        testDirectory,
        target_size = targetSize,
        batch_size=1,  # A batch size of 1 ensures that all test images are processed
        class_mode='categorical',
        shuffle=False
    )

    # Predict categories
    predictions =model.predict(test_generator)
    print(predictions)
    
    predicted_labels = np.argmax(predictions, axis=1).ravel().tolist()
    print(predicted_labels)
    print(type(test_generator.class_indices))
   
    # Format results and compute classification statistics
    results = Results(test_generator.class_indices, dataset_name=dataset_name)
    accuracy, confusion_matrix, classification = results.compute(test_generator.filenames, test_generator.classes,
                                                                     predicted_labels)
    # Display and save results
    results.print(accuracy, confusion_matrix)

    # if save:
    #     results.save(confusion_matrix, classification, predictions)

In [10]:
predict(cnn,testDirectory,'validation')

Reading test data...
Found 723 images belonging to 5 classes.
723/723 [==============================] - 5s 8ms/step
[[1.4664033e-02 9.1768638e-04 2.8474414e-01 2.7997894e-04 6.6208231e-01]
 [4.1499091e-03 7.0320959e-05 1.1083528e-01 1.0526854e-04 8.2504642e-01]
 [1.6074261e-03 1.0198289e-05 5.2513485e-03 1.1873072e-05 9.8888296e-01]
 ...
 [4.1128496e-05 6.6380170e-07 9.8421991e-01 1.5979525e-02 4.1207232e-04]
 [3.6587619e-05 5.5333589e-07 9.7997355e-01 2.1734463e-02 4.9377582e-04]
 [4.0137882e-05 5.6514347e-07 9.7220707e-01 2.7607296e-02 5.4413028e-04]]
[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 